#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  5 11:49:19 2021

@author: atunkiel
"""

from sens_tape import tape
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('f9ad.csv')

drops = ['Unnamed: 0', 'Unnamed: 0.1', 'RHX_RT unitless', 'Pass Name unitless',
              'nameWellbore', 'name','RGX_RT unitless',
                        'MWD Continuous Azimuth dega']

splits = np.linspace(0.15, 0.8, 30)

truth_array = []
pred_array = []
columns_array = []
score_array = []
for split in splits:
    truth, pred, columns, score = tape(data, split=split,
                                      drops=drops,
                                      index = 'Measured Depth m',
                                      target =  'MWD Continuous Inclination dega',
                                      convert_to_diff = ['MWD Continuous Inclination dega'],
                                      lcs_list = [],
                                      plot_samples = False,
                                      resample='radius',
                                      asel_choice = 'ppscore',
                                      hAttrCount=6)
    
    truth_array.append(truth)
    pred_array.append(pred)
    columns_array.append(columns)
    score_array.append(score)
    
diffs = []

for i in range(len(truth_array)):
    diffs.append(np.average(np.abs(truth_array[i] - pred_array[i]), axis=0))

sns.heatmap(diffs, vmax=1.2, vmin=0, cmap='viridis')
plt.title(np.average(diffs))
plt.show()


